# Generated by Django 5.0.1 on 2024-01-13 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorToEditorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONNECTED', 'CONNECTED'), ('PENDING', 'PENDING'), ('NOTCONNECTED', 'NOTCONNECTED')], default='NOTCONNECTED', max_length=200)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('editor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
