# Generated by Django 5.0.1 on 2024-01-13 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_creatortoeditorlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credentials',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creatortoeditorlink',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creatortoeditorlink',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
